import './reset.css';
import './globals.css';
import type { Metadata } from 'next';
import { Fira_Sans } from 'next/font/google';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const fira = Fira_Sans({
	weight: ['400', '700'],
	style: ['normal', 'italic'],
	subsets: ['latin'],
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={fira.className}>
				<div className="container">
					<Header />
					{children}
					<Footer />
				</div>
			</body>
		</html>
	);
}
